name: home
description: "A starting point for Dart libraries or applications."
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  tosspayments:
    path: ../tosspayments
  coinone_model:
    path: ../../core/coinone_model
  common:
    path: ../../core/common
  # path: ^1.8.0
  go_router: 13.2.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6


dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
