name: Build and deploy flutter web app

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19'
          channel: 'master'

      - name: Install dependencies
        run: flutter pub get

      - run: flutter config --enable-web

      - name: Build web
        run: flutter build web --base-href "/${{ github.event.repository.name }}/"

      - name: Deploy to GitHub Pages
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git --work-tree build/web add --all
          git commit -m "Automatic deployment by github-actions"
          git push origin HEAD:gh_pages --force
